{{ define "catalog_js" -}}
// this file was generated by the go-sfomuseum-maps package
// {{ .LastModified }}

var sfomuseum = sfomuseum || {};
sfomuseum.maps = sfomuseum.maps || {};

sfomuseum.maps.catalog = (function(){

    var _catalog = {{ ToJSON .Catalog }};

    var self = {

	'data': function(){
	    return _catalog;
	},
    };

    return self;
})();
{{ end }}
