{{ define "catalog_js" -}}
/**
 * @namespace sfomuseum.maps.catalog
 * @description Methods for inspect the catalog of SFO Museum (aerial) maps.
 * This file was generated by the go-sfomuseum-maps package, {{ .LastModified }}
 * {{ .Args }}
 */
var sfomuseum = sfomuseum || {};
sfomuseum.maps = sfomuseum.maps || {};

sfomuseum.maps.catalog = (function(){

    var _catalog = {{ ToJSON .Catalog }};

    var self = {

	/**
	 * @function data
         * @memberof sfomuseum.maps.catalog
         * @description Return the raw SFO Museum maps catalog
         * @returns {Object}
         */	
	'data': function(){
	    return _catalog;
	},

	'asYears': function(){
	    console.warn("sfomuseum.maps.catalog.asYears is deprecated, please use sfomuseum.maps.catalog.asDictionary");
	    return self.asDictionary();
	},

	/**
	 * @function asDictionaty
         * @memberof sfomuseum.maps.catalog
         * @description Return the SFO Museum maps catalog as a dictionary whose keys are the year a map represent and whose values are an array of [ min_zoom, max_zoom, source, identifier, label ]
         * @returns {Object}
         */
	'asDictionary': function(){
	    
            const catalog = self.data();
	    const count = catalog.length;

            var years = {};

	    for (var i=0; i < count; i++){
		const details = catalog[i];
		years[ details['year'] ] = [
		    details['min_zoom'],
		    details['max_zoom'],
		    details['source'],
		    details['identifier'],
		    details['label'],
		];
            }

            return years;
	},
    };

    return self;
})();
{{ end }}
